### PR TITLE
Create zh_cn.json

### PR DESCRIPTION
**Pull request by GodGun968**

### CODE REVIEW

**Comment by GrigLog** [comment]
Ching cheng hanji

**Comment by GrigLog** [comment]
I didnt figure out how to merge into default branch instead of 1.18 so I did this

**Comment by GodGun968** [comment]
It's been two years :)

**Comment by GrigLog** [comment]
I was in doubt because I want the whole humanity to eventually speak one language. It doesnt really matter which one - English, Chinese, German, Russian or any other, but English is the best candidate for now because of its popularity. If I want my dream to come true then I should produce as much material as I can in English to make it more appealling to learn. 

(Besides that, your translation takes up several bytes of disk space from all mod users, even if they dont know Chinese.)

But now I think that
1) I am very unlikely to survive to the day when all people will speak one langauge, so I shouldnt bother much about it
2) Chinese is quite popular too, so eliminating it is not a top priority. Maybe it will even overgrow English one day. And for now there is a ton of smaller languages which must be erased (like Laz or Swan)
3) There is at least one person who thinks that Chinese translation would be helpful - you. And you are alive right now, so I decided to support your effort

**Pull request closed without merging**
